language: java
sudo: false
addons: 
apt:
packages:
      - oracle-java8-installer

jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk6
  
script:
  - jdk_switcher use oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)
